### ISSUE TITLE
Is any documentation why your approach is faster than in JDK?

### ISSUE THREAD

**Issue by doom369** [bourgesl/jnumbers#3]
Hello. Would appreciate ifyou share some insights regarding why your `NumberParser.getDouble` is faster than in java. Thanks in advance.

**Comment by bourgesl** [comment]
A bit less precision in the rounding code (few ulps) instead of 1/2 ulp.

**Comment by doom369** [comment]
Yeah, thanks. I already dig into it. However docs always better :).

By the way, I did benchmarking with JMH. Your way is 2x faster for double.
